from .dashboard_view import *
from .home_view import *
from .log_in_view import *
from .log_out_view import *
from .password_view import *
from .profile_view import *
from .sign_up_view import *
from .browse_recipes_view import *
from .profile_page_view import *
from .create_recipe_view import *
from .user_search_view import *
from .recipes_view import *
from .specific_recipe_view import *
from .cupboard_view import *
from .toggle_favourite_view import *