# Generated by Django 5.2.7 on 2025-11-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='colour',
            field=models.CharField(default='#61D0FF', max_length=7),
        ),
    ]
