# Generated by Django 5.2.7 on 2025-12-06 22:37

from django.db import migrations
from recipes.models import Tag

tag_fixtures = [
            {"name": "Vegan", "colour": "#2f88ff"}, 
            {"name": "Vegetarian", "colour": "#0d96b6"},
            {"name": "Gluten-free", "colour": "#d59d4d"},
            {"name": "Quick", "colour":"#b26459"},
            {"name": "Easy", "colour": "#b26459"},
            {"name": "Mediterranean", "colour": "#e9dfec"},
            {"name": "Asian", "colour": "#b3a496"},
            {"name": "Indian", "colour": "#82ae67"},
            {"name": "Dairy-free", "colour": "#f67fcb"},
            {"name": "Nut-free", "colour":"#e8cc2b"}
        ]

def create_tags(apps, schema_editor):
    """Construct default tags for the Tag Model"""
    for tag in tag_fixtures:
        tag_object, created = Tag.objects.get_or_create(
            name=tag["name"],
            defaults={"colour": tag["colour"]}
        )

    # If the tag already existed, update its colour
        if not created:
            tag_object.colour = tag["colour"]
            tag_object.save()
    print("Tag seeding complete")

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_tags, migrations.RunPython.noop)
    ]
