# Generated by Django 5.2.8 on 2025-12-02 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='colour',
            field=models.CharField(default='#61D0FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('NN', 'None'), ('VG', 'Vegetable'), ('SP', 'Spice'), ('HB', 'Herbs'), ('BT', 'Butchery'), ('SF', 'Seafood'), ('EG', 'Egg'), ('DR', 'Dairy'), ('NT', 'Nut'), ('GL', 'Gluten'), ('AL', 'Allum'), ('FR', 'Fruit'), ('PS', 'Pulses'), ('GR', 'Grains'), ('WT', 'Water'), ('ML', 'Minerals')], default='NN', max_length=2),
        ),
        migrations.AlterField(
            model_name='methodstep',
            name='method_text',
            field=models.TextField(max_length='256'),
        ),
        migrations.AlterField(
            model_name='methodstep',
            name='step_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
