# Generated by Django 5.2.7 on 2025-11-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipemethod',
            unique_together={('recipe', 'order')},
        ),
    ]
