# Generated by Django 5.2.7 on 2025-11-22 14:23

from django.db import migrations

def create_default_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    default_tags = ["Vegan", "Vegetarian", "Gluten-free", "Quick", "Easy"]
    for name in default_tags:
        Tag.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_tags)
    ]
