# Generated by Django 5.2.8 on 2025-11-28 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_tag_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodstep',
            name='method_text',
            field=models.TextField(max_length='256'),
        ),
        migrations.AlterField(
            model_name='methodstep',
            name='step_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
