# Generated by Django 5.2.7 on 2025-11-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe'),
        ('recipes', '0002_user_bio_user_rating'),
    ]

    operations = [
    ]
