# Generated by Django 5.2.8 on 2025-11-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_image_alter_user_bio'),
        ('recipes', '0005_favourite'),
    ]

    operations = [
    ]
