# Generated by Django 5.2.7 on 2025-11-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_favourite'),
        ('recipes', '0005_tag_recipe_tags'),
    ]

    operations = [
    ]
