# Generated by Django 5.2.7 on 2025-11-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_image_alter_user_bio'),
        ('recipes', '0006_merge_0005_favourite_0005_tag_recipe_tags'),
    ]

    operations = [
    ]
