# Generated by Django 5.2.7 on 2025-11-18 16:11

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_merge_20251118_1611'),
    ]

    operations = [
    ]
