# Generated by Django 5.2.8 on 2025-11-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_user_following_alter_user_bio'),
        ('recipes', '0009_alter_recipe_img_rating'),
        ('recipes', '0009_comment'),
    ]

    operations = [
    ]
