# Generated by Django 5.2.7 on 2025-11-20 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_likes_alter_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='recipes_favourited', to=settings.AUTH_USER_MODEL),
        ),
    ]
